version: "3"

services:
  client:
    container_name: gaa_client
    image: jacobwhitedev/gulag-anthem-art:client
    networks:
      - ga_art
    expose:
      - 8080
      - 8443
    restart: unless-stopped

  server:
    container_name: gaa_server
    image: jacobwhitedev/gulag-anthem-art:server
    networks:
      - ga_art
    expose:
      - 5000
    restart: always

  ssl:
    container_name: ssl
    image: linuxserver/swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - URL=gulaganthem.com
      - SUBDOMAINS=www
      - VALIDATION=http
      - EMAIL=jacobewhitedev@gmail.com
    ports:
      - 443:443
      - 80:80
    restart: unless-stopped
    volumes:
      - ./proxy:/config/nginx/site-confs/default
    networks:
      - mbr

networks:
  ga_art:
    external: true
